# Generated by Django 5.0.6 on 2024-10-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="next_state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="next_state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
