# Generated by Django 5.0.6 on 2024-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="company",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="telegram_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
